trigger:
- main  # Cette section va déclencher le pipeline sur chaque push dans la branche 'main'

pool:
  vmImage: 'ubuntu-latest'  # Utilisation d'une image Ubuntu pour l'exécution du pipeline

steps:
# Étape pour déployer le Load Balancer
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1'  # Remplace par le nom de ta connexion Azure
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Déploiement du Load Balancer
      az deployment group create --resource-group GroupeRessource1 --template-file $(Build.SourcesDirectory)/loadbalancer.json --parameters $(Build.SourcesDirectory)/parameters.json
    displayName: 'Déployer Load Balancer'

# Étape pour déployer les Machines Virtuelles
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1'  # Remplace par le nom de ta connexion Azure
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Déploiement des Machines Virtuelles
      az deployment group create --resource-group GroupeRessource1 --template-file $(Build.SourcesDirectory)/vms.json --parameters $(Build.SourcesDirectory)/parameters.json
    displayName: 'Déployer Machines Virtuelles'
